
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book-project
    ports:
      - "8080:8080"

  db:
    image: 'postgres:11-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=book-project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: