
services:
  app:
    image: 'book-project:latest'
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - PostgreSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/book-project
    ports:
      - "8080:8080"

  PostgreSQL:
    image: 'postgres:13-alpine'
    container_name: PostgreSQL
    environment:
      - POSTGRES_DB=book-project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: